import '../user_creation_four_screen/widgets/grid_item_widget.dart';import 'bloc/user_creation_four_bloc.dart';import 'models/grid_item_model.dart';import 'models/user_creation_four_model.dart';import 'package:flutter/material.dart';import 'package:samruddhi_s_application1/core/app_export.dart';import 'package:samruddhi_s_application1/widgets/app_bar/appbar_image.dart';import 'package:samruddhi_s_application1/widgets/app_bar/appbar_subtitle_1.dart';import 'package:samruddhi_s_application1/widgets/app_bar/appbar_title.dart';import 'package:samruddhi_s_application1/widgets/app_bar/custom_app_bar.dart';class UserCreationFourScreen extends StatelessWidget {const UserCreationFourScreen({Key? key}) : super(key: key);

static Widget builder(BuildContext context) { return BlocProvider<UserCreationFourBloc>(create: (context) => UserCreationFourBloc(UserCreationFourState(userCreationFourModelObj: UserCreationFourModel()))..add(UserCreationFourInitialEvent()), child: UserCreationFourScreen()); } 
@override Widget build(BuildContext context) { mediaQueryData = MediaQuery.of(context); return SafeArea(child: Scaffold(extendBody: true, extendBodyBehindAppBar: true, backgroundColor: theme.colorScheme.onPrimary.withOpacity(1), appBar: CustomAppBar(height: getVerticalSize(33), leadingWidth: getHorizontalSize(35), leading: AppbarImage(imagePath: ImageConstant.imgRightarrow11, margin: getMargin(left: 15, top: 10, bottom: 3)), centerTitle: true, title: AppbarTitle(text: "msg9".tr), actions: [GestureDetector(onTap: () {onTapRowenglish(context);}, child: Container(margin: getMargin(left: 15, top: 13, right: 15, bottom: 6), padding: getPadding(left: 2, right: 2), decoration: AppDecoration.outlineOrange500.copyWith(borderRadius: BorderRadiusStyle.roundedBorder2), child: Row(mainAxisAlignment: MainAxisAlignment.center, children: [AppbarSubtitle1(text: "lbl_english".tr, margin: getMargin(left: 2, top: 1)), Container(height: getSize(10), width: getSize(10), margin: getMargin(left: 2, top: 2, bottom: 2), decoration: BoxDecoration(color: appTheme.orange500, borderRadius: BorderRadius.circular(getHorizontalSize(2))))])))]), body: Container(width: mediaQueryData.size.width, height: mediaQueryData.size.height, decoration: BoxDecoration(color: theme.colorScheme.onPrimary.withOpacity(1), image: DecorationImage(image: AssetImage(ImageConstant.imgUsercreation), fit: BoxFit.cover)), child: Container(width: double.maxFinite, padding: getPadding(left: 29, top: 20, right: 29, bottom: 20), child: Column(crossAxisAlignment: CrossAxisAlignment.start, mainAxisAlignment: MainAxisAlignment.start, children: [Text("msg10".tr, style: theme.textTheme.titleLarge), Expanded(child: Padding(padding: getPadding(top: 15), child: BlocSelector<UserCreationFourBloc, UserCreationFourState, UserCreationFourModel?>(selector: (state) => state.userCreationFourModelObj, builder: (context, userCreationFourModelObj) {return GridView.builder(shrinkWrap: true, gridDelegate: SliverGridDelegateWithFixedCrossAxisCount(mainAxisExtent: getVerticalSize(111), crossAxisCount: 3, mainAxisSpacing: getHorizontalSize(15), crossAxisSpacing: getHorizontalSize(15)), physics: BouncingScrollPhysics(), itemCount: userCreationFourModelObj?.gridItemList.length ?? 0, itemBuilder: (context, index) {GridItemModel model = userCreationFourModelObj?.gridItemList[index] ?? GridItemModel(); return GridItemWidget(model, onTapColumn: () {onTapColumn(context);});});})))]))))); } 
/// Navigates to the myBadiBahenOneScreen when the action is triggered.
///
/// The [BuildContext] parameter is used to build the navigation stack.
/// When the action is triggered, this function uses the [NavigatorService]
/// to push the named route for the myBadiBahenOneScreen.
onTapColumn(BuildContext context) { NavigatorService.pushNamed(AppRoutes.myBadiBahenOneScreen); } 
/// Navigates to the userCreationThreeScreen when the action is triggered.
///
/// The [BuildContext] parameter is used to build the navigation stack.
/// When the action is triggered, this function uses the [NavigatorService]
/// to push the named route for the userCreationThreeScreen.
onTapRowenglish(BuildContext context) { NavigatorService.pushNamed(AppRoutes.userCreationThreeScreen, ); } 
 }
