import '../user_creation_one_screen/widgets/user_creation_item_widget.dart';import 'bloc/user_creation_one_bloc.dart';import 'models/user_creation_item_model.dart';import 'models/user_creation_one_model.dart';import 'package:flutter/material.dart';import 'package:samruddhi_s_application1/core/app_export.dart';import 'package:samruddhi_s_application1/widgets/app_bar/appbar_image.dart';import 'package:samruddhi_s_application1/widgets/app_bar/appbar_subtitle_2.dart';import 'package:samruddhi_s_application1/widgets/app_bar/appbar_title.dart';import 'package:samruddhi_s_application1/widgets/app_bar/custom_app_bar.dart';class UserCreationOneScreen extends StatelessWidget {const UserCreationOneScreen({Key? key}) : super(key: key);

static Widget builder(BuildContext context) { return BlocProvider<UserCreationOneBloc>(create: (context) => UserCreationOneBloc(UserCreationOneState(userCreationOneModelObj: UserCreationOneModel()))..add(UserCreationOneInitialEvent()), child: UserCreationOneScreen()); } 
@override Widget build(BuildContext context) { mediaQueryData = MediaQuery.of(context); return SafeArea(child: Scaffold(extendBody: true, extendBodyBehindAppBar: true, backgroundColor: theme.colorScheme.onPrimary.withOpacity(1), appBar: CustomAppBar(height: getVerticalSize(37), leadingWidth: getHorizontalSize(35), leading: AppbarImage(imagePath: ImageConstant.imgRightarrow11, margin: getMargin(left: 15, top: 10, bottom: 7), onTap: () {onTapRightarroweleve(context);}), centerTitle: true, title: AppbarTitle(text: "lbl_create_account".tr), actions: [Container(margin: getMargin(left: 15, top: 13, right: 15, bottom: 10), padding: getPadding(left: 2, right: 2), decoration: AppDecoration.outlineOrange500.copyWith(borderRadius: BorderRadiusStyle.roundedBorder2), child: Row(mainAxisAlignment: MainAxisAlignment.center, children: [Container(height: getSize(10), width: getSize(10), margin: getMargin(top: 2, bottom: 2), decoration: BoxDecoration(color: appTheme.orange500, borderRadius: BorderRadius.circular(getHorizontalSize(2)))), AppbarSubtitle2(text: "lbl7".tr.toUpperCase(), margin: getMargin(left: 4, right: 5, bottom: 1))]))]), body: Container(width: mediaQueryData.size.width, height: mediaQueryData.size.height, decoration: BoxDecoration(color: theme.colorScheme.onPrimary.withOpacity(1), image: DecorationImage(image: AssetImage(ImageConstant.imgUsercreation), fit: BoxFit.cover)), child: Container(width: double.maxFinite, padding: getPadding(left: 30, top: 20, right: 30, bottom: 20), child: Column(crossAxisAlignment: CrossAxisAlignment.start, mainAxisAlignment: MainAxisAlignment.start, children: [Text("msg_choose_your_profession".tr, style: theme.textTheme.titleLarge), Expanded(child: Padding(padding: getPadding(top: 11), child: BlocSelector<UserCreationOneBloc, UserCreationOneState, UserCreationOneModel?>(selector: (state) => state.userCreationOneModelObj, builder: (context, userCreationOneModelObj) {return GridView.builder(shrinkWrap: true, gridDelegate: SliverGridDelegateWithFixedCrossAxisCount(mainAxisExtent: getVerticalSize(111), crossAxisCount: 3, mainAxisSpacing: getHorizontalSize(15), crossAxisSpacing: getHorizontalSize(15)), physics: BouncingScrollPhysics(), itemCount: userCreationOneModelObj?.userCreationItemList.length ?? 0, itemBuilder: (context, index) {UserCreationItemModel model = userCreationOneModelObj?.userCreationItemList[index] ?? UserCreationItemModel(); return UserCreationItemWidget(model);});})))]))))); } 
/// Navigates to the otpScreen when the action is triggered.
///
/// The [BuildContext] parameter is used to build the navigation stack.
/// When the action is triggered, this function uses the [NavigatorService]
/// to push the named route for the otpScreen.
onTapRightarroweleve(BuildContext context) { NavigatorService.pushNamed(AppRoutes.otpScreen, ); } 
 }
