import 'bloc/terms_condition_bloc.dart';import 'models/terms_condition_model.dart';import 'package:flutter/material.dart';import 'package:samruddhi_s_application1/core/app_export.dart';import 'package:samruddhi_s_application1/widgets/app_bar/appbar_image.dart';import 'package:samruddhi_s_application1/widgets/app_bar/appbar_subtitle_2.dart';import 'package:samruddhi_s_application1/widgets/app_bar/appbar_title.dart';import 'package:samruddhi_s_application1/widgets/app_bar/custom_app_bar.dart';class TermsConditionScreen extends StatelessWidget {const TermsConditionScreen({Key? key}) : super(key: key);

static Widget builder(BuildContext context) { return BlocProvider<TermsConditionBloc>(create: (context) => TermsConditionBloc(TermsConditionState(termsConditionModelObj: TermsConditionModel()))..add(TermsConditionInitialEvent()), child: TermsConditionScreen()); } 
@override Widget build(BuildContext context) { mediaQueryData = MediaQuery.of(context); return BlocBuilder<TermsConditionBloc, TermsConditionState>(builder: (context, state) {return SafeArea(child: Scaffold(backgroundColor: theme.colorScheme.onPrimary.withOpacity(1), appBar: CustomAppBar(leadingWidth: getHorizontalSize(35), leading: AppbarImage(imagePath: ImageConstant.imgLeftarrow1, margin: getMargin(left: 15, top: 10, bottom: 10), onTap: () {onTapLeftarrowone(context);}), centerTitle: true, title: AppbarTitle(text: "msg_terms_conditions".tr), actions: [Container(margin: getMargin(left: 15, top: 13, right: 15, bottom: 13), padding: getPadding(left: 2, right: 2), decoration: AppDecoration.outlineOrange5003.copyWith(borderRadius: BorderRadiusStyle.roundedBorder2), child: Row(mainAxisAlignment: MainAxisAlignment.center, children: [Container(height: getSize(10), width: getSize(10), margin: getMargin(top: 2, bottom: 2), decoration: BoxDecoration(color: appTheme.orange500, borderRadius: BorderRadius.circular(getHorizontalSize(2)))), AppbarSubtitle2(text: "lbl5".tr.toUpperCase(), margin: getMargin(left: 2, top: 1, right: 2))]))], styleType: Style.bgFill), body: Container(width: double.maxFinite, padding: getPadding(left: 12, top: 9, right: 12, bottom: 9), child: Column(mainAxisAlignment: MainAxisAlignment.start, children: [Container(width: getHorizontalSize(330), margin: getMargin(left: 3, right: 3), child: RichText(text: TextSpan(children: [TextSpan(text: "msg_terms_and_condition".tr, style: CustomTextStyles.titleMediumBlack90001), TextSpan(text: "msg_lorem_ipsum_is_simply3".tr, style: CustomTextStyles.bodySmallBluegray8000112_1)]), textAlign: TextAlign.justify)), Container(width: getHorizontalSize(330), margin: getMargin(left: 3, top: 7, right: 3), child: RichText(text: TextSpan(children: [TextSpan(text: "msg_why_do_we_use_it".tr, style: CustomTextStyles.titleMediumBlack90001), TextSpan(text: "msg_it_is_a_long_established3".tr, style: CustomTextStyles.bodySmallBluegray8000112_1)]), textAlign: TextAlign.justify)), Container(width: getHorizontalSize(330), margin: getMargin(top: 7, right: 6, bottom: 5), child: RichText(text: TextSpan(children: [TextSpan(text: "msg_where_does_it_come2".tr, style: CustomTextStyles.titleMediumBlack90001), TextSpan(text: "msg_it_is_a_long_established3".tr, style: CustomTextStyles.bodySmallBluegray8000112_1)]), textAlign: TextAlign.justify))]))));}); } 
/// Navigates to the dashboardScreen when the action is triggered.
///
/// The [BuildContext] parameter is used to build the navigation stack.
/// When the action is triggered, this function uses the [NavigatorService]
/// to push the named route for the dashboardScreen.
onTapLeftarrowone(BuildContext context) { NavigatorService.pushNamed(AppRoutes.dashboardScreen, ); } 
 }
