import '../user_creation_two_screen/widgets/user_creation1_item_widget.dart';import 'bloc/user_creation_two_bloc.dart';import 'models/user_creation1_item_model.dart';import 'models/user_creation_two_model.dart';import 'package:flutter/material.dart';import 'package:samruddhi_s_application1/core/app_export.dart';import 'package:samruddhi_s_application1/widgets/app_bar/appbar_image.dart';import 'package:samruddhi_s_application1/widgets/app_bar/appbar_subtitle_1.dart';import 'package:samruddhi_s_application1/widgets/app_bar/appbar_title.dart';import 'package:samruddhi_s_application1/widgets/app_bar/custom_app_bar.dart';class UserCreationTwoScreen extends StatelessWidget {const UserCreationTwoScreen({Key? key}) : super(key: key);

static Widget builder(BuildContext context) { return BlocProvider<UserCreationTwoBloc>(create: (context) => UserCreationTwoBloc(UserCreationTwoState(userCreationTwoModelObj: UserCreationTwoModel()))..add(UserCreationTwoInitialEvent()), child: UserCreationTwoScreen()); } 
@override Widget build(BuildContext context) { mediaQueryData = MediaQuery.of(context); return SafeArea(child: Scaffold(extendBody: true, extendBodyBehindAppBar: true, backgroundColor: theme.colorScheme.onPrimary.withOpacity(1), appBar: CustomAppBar(height: getVerticalSize(34), leadingWidth: getHorizontalSize(35), leading: AppbarImage(imagePath: ImageConstant.imgRightarrow11, margin: getMargin(left: 15, top: 10, bottom: 4)), centerTitle: true, title: AppbarTitle(text: "lbl9".tr), actions: [Container(margin: getMargin(left: 11, top: 13, right: 11, bottom: 7), padding: getPadding(left: 2, right: 2), decoration: AppDecoration.outlineOrange500.copyWith(borderRadius: BorderRadiusStyle.roundedBorder2), child: Row(mainAxisAlignment: MainAxisAlignment.center, children: [AppbarSubtitle1(text: "lbl_english".tr, margin: getMargin(left: 2, top: 1)), Container(height: getSize(10), width: getSize(10), margin: getMargin(left: 2, top: 2, bottom: 2), decoration: BoxDecoration(color: appTheme.orange500, borderRadius: BorderRadius.circular(getHorizontalSize(2))))]))]), body: Container(width: mediaQueryData.size.width, height: mediaQueryData.size.height, decoration: BoxDecoration(color: theme.colorScheme.onPrimary.withOpacity(1), image: DecorationImage(image: AssetImage(ImageConstant.imgUsercreation), fit: BoxFit.cover)), child: Container(width: double.maxFinite, padding: getPadding(left: 30, top: 22, right: 30, bottom: 22), child: Column(crossAxisAlignment: CrossAxisAlignment.start, mainAxisAlignment: MainAxisAlignment.start, children: [Text("lbl10".tr, style: theme.textTheme.titleLarge), Expanded(child: Padding(padding: getPadding(top: 12), child: BlocSelector<UserCreationTwoBloc, UserCreationTwoState, UserCreationTwoModel?>(selector: (state) => state.userCreationTwoModelObj, builder: (context, userCreationTwoModelObj) {return GridView.builder(shrinkWrap: true, gridDelegate: SliverGridDelegateWithFixedCrossAxisCount(mainAxisExtent: getVerticalSize(111), crossAxisCount: 3, mainAxisSpacing: getHorizontalSize(15), crossAxisSpacing: getHorizontalSize(15)), physics: BouncingScrollPhysics(), itemCount: userCreationTwoModelObj?.userCreation1ItemList.length ?? 0, itemBuilder: (context, index) {UserCreation1ItemModel model = userCreationTwoModelObj?.userCreation1ItemList[index] ?? UserCreation1ItemModel(); return UserCreation1ItemWidget(model, onTapColumn: () {onTapColumn(context);});});})))]))))); } 
/// Navigates to the myBadiBahenOneScreen when the action is triggered.
///
/// The [BuildContext] parameter is used to build the navigation stack.
/// When the action is triggered, this function uses the [NavigatorService]
/// to push the named route for the myBadiBahenOneScreen.
onTapColumn(BuildContext context) { NavigatorService.pushNamed(AppRoutes.myBadiBahenOneScreen, ); } 
 }
