import '../user_creation_three_screen/widgets/gridselfemploye_item_widget.dart';import 'bloc/user_creation_three_bloc.dart';import 'models/gridselfemploye_item_model.dart';import 'models/user_creation_three_model.dart';import 'package:flutter/material.dart';import 'package:samruddhi_s_application1/core/app_export.dart';import 'package:samruddhi_s_application1/widgets/app_bar/appbar_image.dart';import 'package:samruddhi_s_application1/widgets/app_bar/appbar_subtitle_1.dart';import 'package:samruddhi_s_application1/widgets/app_bar/appbar_title.dart';import 'package:samruddhi_s_application1/widgets/app_bar/custom_app_bar.dart';class UserCreationThreeScreen extends StatelessWidget {const UserCreationThreeScreen({Key? key}) : super(key: key);

static Widget builder(BuildContext context) { return BlocProvider<UserCreationThreeBloc>(create: (context) => UserCreationThreeBloc(UserCreationThreeState(userCreationThreeModelObj: UserCreationThreeModel()))..add(UserCreationThreeInitialEvent()), child: UserCreationThreeScreen()); } 
@override Widget build(BuildContext context) { mediaQueryData = MediaQuery.of(context); return SafeArea(child: Scaffold(extendBody: true, extendBodyBehindAppBar: true, backgroundColor: theme.colorScheme.onPrimary.withOpacity(1), appBar: CustomAppBar(height: getVerticalSize(37), leadingWidth: getHorizontalSize(35), leading: AppbarImage(imagePath: ImageConstant.imgRightarrow11, margin: getMargin(left: 15, top: 10, bottom: 7), onTap: () {onTapRightarroweleve(context);}), centerTitle: true, title: AppbarTitle(text: "lbl_create_account".tr), actions: [GestureDetector(onTap: () {onTapRowview(context);}, child: Container(margin: getMargin(left: 15, top: 13, right: 15, bottom: 10), padding: getPadding(left: 2, right: 2), decoration: AppDecoration.outlineOrange500.copyWith(borderRadius: BorderRadiusStyle.roundedBorder2), child: Row(mainAxisAlignment: MainAxisAlignment.center, children: [Container(height: getSize(10), width: getSize(10), margin: getMargin(top: 2, bottom: 2), decoration: BoxDecoration(color: appTheme.orange500, borderRadius: BorderRadius.circular(getHorizontalSize(2)))), AppbarSubtitle1(text: "lbl5".tr.toUpperCase(), margin: getMargin(left: 3, right: 1, bottom: 1))])))]), body: Container(width: mediaQueryData.size.width, height: mediaQueryData.size.height, decoration: BoxDecoration(color: theme.colorScheme.onPrimary.withOpacity(1), image: DecorationImage(image: AssetImage(ImageConstant.imgUsercreation), fit: BoxFit.cover)), child: Container(width: double.maxFinite, padding: getPadding(left: 30, top: 20, right: 30, bottom: 20), child: Column(crossAxisAlignment: CrossAxisAlignment.start, mainAxisAlignment: MainAxisAlignment.start, children: [Text("msg_choose_your_profession".tr, style: theme.textTheme.titleLarge), Expanded(child: Padding(padding: getPadding(top: 11), child: BlocSelector<UserCreationThreeBloc, UserCreationThreeState, UserCreationThreeModel?>(selector: (state) => state.userCreationThreeModelObj, builder: (context, userCreationThreeModelObj) {return GridView.builder(shrinkWrap: true, gridDelegate: SliverGridDelegateWithFixedCrossAxisCount(mainAxisExtent: getVerticalSize(111), crossAxisCount: 3, mainAxisSpacing: getHorizontalSize(15), crossAxisSpacing: getHorizontalSize(15)), physics: BouncingScrollPhysics(), itemCount: userCreationThreeModelObj?.gridselfemployeItemList.length ?? 0, itemBuilder: (context, index) {GridselfemployeItemModel model = userCreationThreeModelObj?.gridselfemployeItemList[index] ?? GridselfemployeItemModel(); return GridselfemployeItemWidget(model, onTapColumnselfemplo: () {onTapColumnselfemplo(context);});});})))]))))); } 
/// Navigates to the myBadiBahenOneScreen when the action is triggered.
///
/// The [BuildContext] parameter is used to build the navigation stack.
/// When the action is triggered, this function uses the [NavigatorService]
/// to push the named route for the myBadiBahenOneScreen.
onTapColumnselfemplo(BuildContext context) { NavigatorService.pushNamed(AppRoutes.myBadiBahenOneScreen); } 
/// Navigates to the otpOneScreen when the action is triggered.
///
/// The [BuildContext] parameter is used to build the navigation stack.
/// When the action is triggered, this function uses the [NavigatorService]
/// to push the named route for the otpOneScreen.
onTapRightarroweleve(BuildContext context) { NavigatorService.pushNamed(AppRoutes.otpOneScreen, ); } 
/// Navigates to the userCreationFourScreen when the action is triggered.
///
/// The [BuildContext] parameter is used to build the navigation stack.
/// When the action is triggered, this function uses the [NavigatorService]
/// to push the named route for the userCreationFourScreen.
onTapRowview(BuildContext context) { NavigatorService.pushNamed(AppRoutes.userCreationFourScreen, ); } 
 }
