import '../number_details_page/widgets/number_details_item_widget.dart';import 'bloc/number_details_bloc.dart';import 'models/number_details_item_model.dart';import 'models/number_details_model.dart';import 'package:flutter/material.dart';import 'package:samruddhi_s_application1/core/app_export.dart';import 'package:samruddhi_s_application1/widgets/custom_elevated_button.dart';class NumberDetailsPage extends StatefulWidget {const NumberDetailsPage({Key? key}) : super(key: key);

@override NumberDetailsPageState createState() =>  NumberDetailsPageState();
static Widget builder(BuildContext context) { return BlocProvider<NumberDetailsBloc>(create: (context) => NumberDetailsBloc(NumberDetailsState(numberDetailsModelObj: NumberDetailsModel()))..add(NumberDetailsInitialEvent()), child: NumberDetailsPage()); } 
 }
class NumberDetailsPageState extends State<NumberDetailsPage> with  AutomaticKeepAliveClientMixin<NumberDetailsPage> {@override bool get wantKeepAlive =>  true;
@override Widget build(BuildContext context) { mediaQueryData = MediaQuery.of(context); return SafeArea(child: Scaffold(backgroundColor: theme.colorScheme.onPrimary.withOpacity(1), body: SizedBox(width: mediaQueryData.size.width, child: SingleChildScrollView(child: Column(mainAxisAlignment: MainAxisAlignment.start, children: [Padding(padding: getPadding(left: 15, top: 10, right: 15), child: Column(mainAxisAlignment: MainAxisAlignment.start, children: [Expanded(child: SizedBox(width: double.maxFinite, child: Container(decoration: AppDecoration.outlineOrange500.copyWith(borderRadius: BorderRadiusStyle.roundedBorder5), child: Column(mainAxisSize: MainAxisSize.min, crossAxisAlignment: CrossAxisAlignment.start, mainAxisAlignment: MainAxisAlignment.start, children: [Container(padding: getPadding(left: 10, top: 2, right: 10, bottom: 2), decoration: AppDecoration.fillOrange, child: Row(mainAxisAlignment: MainAxisAlignment.center, children: [CustomImageView(imagePath: ImageConstant.imgAccount1, height: getSize(14), width: getSize(14), margin: getMargin(top: 5, bottom: 5)), Padding(padding: getPadding(left: 5, bottom: 2), child: Text("lbl_number_details".tr, style: CustomTextStyles.titleSmallOnPrimary_1)), Spacer(), CustomImageView(svgPath: ImageConstant.imgEdit, height: getSize(12), width: getSize(12), margin: getMargin(top: 6, right: 1, bottom: 5))])), Expanded(child: Padding(padding: getPadding(left: 15, top: 6, right: 52, bottom: 13), child: BlocSelector<NumberDetailsBloc, NumberDetailsState, NumberDetailsModel?>(selector: (state) => state.numberDetailsModelObj, builder: (context, numberDetailsModelObj) {return ListView.builder(physics: BouncingScrollPhysics(), shrinkWrap: true, itemCount: numberDetailsModelObj?.numberDetailsItemList.length ?? 0, itemBuilder: (context, index) {NumberDetailsItemModel model = numberDetailsModelObj?.numberDetailsItemList[index] ?? NumberDetailsItemModel(); return NumberDetailsItemWidget(model);});})))])))), CustomElevatedButton(width: getHorizontalSize(160), text: "lbl_submit".tr, margin: getMargin(top: 15), onTap: () {onTapSubmit(context);})]))]))))); } 
/// Navigates to the dashboardScreen when the action is triggered.
///
/// The [BuildContext] parameter is used to build the navigation stack.
/// When the action is triggered, this function uses the [NavigatorService]
/// to push the named route for the dashboardScreen.
onTapSubmit(BuildContext context) { NavigatorService.pushNamed(AppRoutes.dashboardScreen, ); } 
 }
